### ISSUE TITLE
Utils to visualize fig.1 (a) in the paper

### ISSUE THREAD

**Issue by DachunKai** [redrock303/ADF-LLIE#3]
Hi, could you provide the script to get Fig. 1(a) in the paper? Given an image, how did you get low-frequency and high-frequency regions? Thanks a lot.

**Comment by redrock303** [comment]
You can use the pytorch function PyLap as indicated in this command "from utils.modules.pyramid_lap import PyLap".
It contains the Laplace transformation and inverse Laplace transformation. The Laplace transformation can decompose an RGB image into different low- and high-frequency maps.
